// Generated from the current WebP Gallery folder.
window.WEDDING_GALLERY = [
  { src: 'Gallery/BEN_2443.webp', alt: 'Galeri Virginia dan Faisal 1' },
  { src: 'Gallery/BEN_2530-2.webp', alt: 'Galeri Virginia dan Faisal 2' },
  { src: 'Gallery/BEN_2549.webp', alt: 'Galeri Virginia dan Faisal 3' },
  { src: 'Gallery/BEN_2565.webp', alt: 'Galeri Virginia dan Faisal 4' },
  { src: 'Gallery/BEN_2571.webp', alt: 'Galeri Virginia dan Faisal 5' },
  { src: 'Gallery/BEN_2599.webp', alt: 'Galeri Virginia dan Faisal 6' },
  { src: 'Gallery/BEN_2651.webp', alt: 'Galeri Virginia dan Faisal 7' },
  { src: 'Gallery/BEN_2701.webp', alt: 'Galeri Virginia dan Faisal 8' },
  { src: 'Gallery/BEN_2707.webp', alt: 'Galeri Virginia dan Faisal 9' },
  { src: 'Gallery/BEN_2720.webp', alt: 'Galeri Virginia dan Faisal 10' },
  { src: 'Gallery/BEN_2809.webp', alt: 'Galeri Virginia dan Faisal 11' },
  { src: 'Gallery/BEN_2823.webp', alt: 'Galeri Virginia dan Faisal 12' },
  { src: 'Gallery/BEN_2882.webp', alt: 'Galeri Virginia dan Faisal 13' },
  { src: 'Gallery/BEN_2954.webp', alt: 'Galeri Virginia dan Faisal 14' },
  { src: 'Gallery/BEN_2968.webp', alt: 'Galeri Virginia dan Faisal 15' },
  { src: 'Gallery/BEN_3004.webp', alt: 'Galeri Virginia dan Faisal 16' },
  { src: 'Gallery/BEN_3067.webp', alt: 'Galeri Virginia dan Faisal 17' },
  { src: 'Gallery/BEN_3138.webp', alt: 'Galeri Virginia dan Faisal 18' },
  { src: 'Gallery/BEN_3281.webp', alt: 'Galeri Virginia dan Faisal 19' },
  { src: 'Gallery/BEN_3348.webp', alt: 'Galeri Virginia dan Faisal 20' },
  { src: 'Gallery/BEN_33742.webp', alt: 'Galeri Virginia dan Faisal 21' },
  { src: 'Gallery/BEN_3381.webp', alt: 'Galeri Virginia dan Faisal 22' },
  { src: 'Gallery/cec00d75-3b51-469a-b6b5-25683ac7cc892.webp', alt: 'Galeri Virginia dan Faisal 23' },
];
