// Generated from the current resized Gallery folder.
window.WEDDING_GALLERY = [
  { src: 'Gallery/BEN_2282.jpg', alt: 'Galeri Virgina dan Faisal 1' },
  { src: 'Gallery/BEN_2427.jpg', alt: 'Galeri Virgina dan Faisal 2' },
  { src: 'Gallery/BEN_2443.jpg', alt: 'Galeri Virgina dan Faisal 3' },
  { src: 'Gallery/BEN_2465.jpg', alt: 'Galeri Virgina dan Faisal 4' },
  { src: 'Gallery/BEN_2500.jpg', alt: 'Galeri Virgina dan Faisal 5' },
  { src: 'Gallery/BEN_2530-2.jpg', alt: 'Galeri Virgina dan Faisal 6' },
  { src: 'Gallery/BEN_2549.jpg', alt: 'Galeri Virgina dan Faisal 7' },
  { src: 'Gallery/BEN_2565.jpg', alt: 'Galeri Virgina dan Faisal 8' },
  { src: 'Gallery/BEN_2571.jpg', alt: 'Galeri Virgina dan Faisal 9' },
  { src: 'Gallery/BEN_2599.jpg', alt: 'Galeri Virgina dan Faisal 10' },
  { src: 'Gallery/BEN_2651.jpg', alt: 'Galeri Virgina dan Faisal 11' },
  { src: 'Gallery/BEN_2701.jpg', alt: 'Galeri Virgina dan Faisal 12' },
  { src: 'Gallery/BEN_2707.jpg', alt: 'Galeri Virgina dan Faisal 13' },
  { src: 'Gallery/BEN_2720.jpg', alt: 'Galeri Virgina dan Faisal 14' },
  { src: 'Gallery/BEN_2759.jpg', alt: 'Galeri Virgina dan Faisal 15' },
  { src: 'Gallery/BEN_2802.jpg', alt: 'Galeri Virgina dan Faisal 16' },
  { src: 'Gallery/BEN_2809.jpg', alt: 'Galeri Virgina dan Faisal 17' },
  { src: 'Gallery/BEN_2823.jpg', alt: 'Galeri Virgina dan Faisal 18' },
  { src: 'Gallery/BEN_2882.jpg', alt: 'Galeri Virgina dan Faisal 19' },
  { src: 'Gallery/BEN_2908.jpg', alt: 'Galeri Virgina dan Faisal 20' },
  { src: 'Gallery/BEN_2954.jpg', alt: 'Galeri Virgina dan Faisal 21' },
  { src: 'Gallery/BEN_2968.jpg', alt: 'Galeri Virgina dan Faisal 22' },
  { src: 'Gallery/BEN_3004.jpg', alt: 'Galeri Virgina dan Faisal 23' },
  { src: 'Gallery/BEN_3067.jpg', alt: 'Galeri Virgina dan Faisal 24' },
  { src: 'Gallery/BEN_3138.jpg', alt: 'Galeri Virgina dan Faisal 25' },
  { src: 'Gallery/BEN_3281.jpg', alt: 'Galeri Virgina dan Faisal 26' },
  { src: 'Gallery/BEN_3337.jpg', alt: 'Galeri Virgina dan Faisal 27' },
  { src: 'Gallery/BEN_3348.jpg', alt: 'Galeri Virgina dan Faisal 28' },
  { src: 'Gallery/BEN_33742.jpg', alt: 'Galeri Virgina dan Faisal 29' },
  { src: 'Gallery/BEN_3381.jpg', alt: 'Galeri Virgina dan Faisal 30' },
  { src: 'Gallery/BEN_3397.jpg', alt: 'Galeri Virgina dan Faisal 31' },
  { src: 'Gallery/BEN_3414.jpg', alt: 'Galeri Virgina dan Faisal 32' },
  { src: 'Gallery/cec00d75-3b51-469a-b6b5-25683ac7cc892.png', alt: 'Galeri Virgina dan Faisal 33' },
];
